#!/bin/bash
echo "=== 1. 安装等待器结果 ==="
cat /tmp/install_wait.txt 2>/dev/null || echo "等待器文件不存在"
echo ""
echo "=== 2. 安装日志尾部 ==="
tail -6 /tmp/owui_install2.log 2>/dev/null
echo ""
echo "=== 3. pip 进程 ==="
ps aux | grep "pip install" | grep -v grep | head -2 || echo "无 pip 进程"
echo ""
echo "=== 4. 新 venv 版本 ==="
/usr/local/open-webui-venv/bin/pip show open-webui 2>/dev/null | head -2 || echo "open-webui 未安装"
/usr/local/open-webui-venv/bin/pip show chromadb 2>/dev/null | head -2 || echo "chromadb 未安装"
echo ""
echo "=== 5. open-webui 命令存在性 ==="
ls -la /usr/local/open-webui-venv/bin/open-webui 2>/dev/null || echo "无 open-webui 命令"
